### PR TITLE
Use the proper CMake path constants to avoid conflicts

### LINKED ISSUE #5: Replace CMAKE_SOURCE_DIR with CMAKE_CURRENT_SOURCE_DIR
`CMake` is currently configured to use `CMAKE_SOURCE_DIR`
Conflicts may arise when the library is imported (for example, using [CPM](https://github.com/cpm-cmake/CPM.cmake))
It is necessary to change every instance of `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR` in order to prevent the latter

### PR DESCRIPTION
**Pull request by vahancho**
Adjust the CMake script too.

fixes #5

### CODE REVIEW

**Comment by carlocorradini** [comment]
I think it's better to keep `include` and `src` directories separated 

PS: See #7

**Comment by vahancho** [comment]
> I think it's better to keep `include` and `src` directories separated

Why?

**Comment by carlocorradini** [comment]
Best practice (mostly every C++ codebase) 🥳

**Comment by vahancho** [comment]
In fact the `include` directory is still separated. It's just moved into the `src/` directory where **all** sources reside.

UPDATE:

Anyways, I reverted the move of the include directory leaving it where it was and only changed the CMakeLists.txt.

**Pull request merged**
